--9.	請將題9新增的借閱紀錄(書本ID=2004)刪除

BEGIN TRY
	BEGIN TRANSACTION
		DELETE FROM BOOK_LEND_RECORD WHERE BOOK_ID=2004 AND KEEPER_ID=(SELECT USER_ID FROM MEMBER_M WHERE USER_CNAME='李四');
	COMMIT TRANSACTION
END TRY

BEGIN CATCH
	SELECT ERROR_MESSAGE()
	ROLLBACK TRANSACTION
END CATCH

SELECT bd.BOOK_ID AS 書本ID,
	CONVERT(VARCHAR(10),bd.BOOK_BOUGHT_DATE,111) AS 購書日期,
	CONVERT(VARCHAR(10),blr.LEND_DATE,111) AS 借閱日期,
	bcla.BOOK_CLASS_ID + '-' + bcla.BOOK_CLASS_NAME AS 書籍類別,
	blr.KEEPER_ID+'-'+mm.USER_CNAME+'('+mm.USER_ENAME+')' AS 借閱人,
	bd.BOOK_STATUS + '-' + bcod.CODE_NAME AS 狀態,
	REPLACE(CONVERT(NVARCHAR(20),CAST(bd.BOOK_AMOUNT AS Money) ,1),'.00','') + '元' AS 購買金額
FROM BOOK_LEND_RECORD AS blr
	INNER JOIN BOOK_DATA AS bd
		ON blr.BOOK_ID = bd.BOOK_ID
	INNER JOIN MEMBER_M AS mm
		ON blr.KEEPER_ID = mm.[USER_ID]
	INNER JOIN BOOK_CLASS AS bcla
		ON bd.BOOK_CLASS_ID = bcla.BOOK_CLASS_ID
	INNER JOIN BOOK_CODE AS bcod
		ON bd.BOOK_STATUS =  bcod.CODE_ID AND bcod.CODE_TYPE='BOOK_STATUS'
WHERE blr.KEEPER_ID = 0002
ORDER BY bd.BOOK_AMOUNT DESC